[package]
name = "intra"
authors = ["Simone Walter <waltersz@protonmail.com>"]
version = "0.1.0"
edition = "2021"
description = "The intergalactic numeric translator"

[dependencies]
rust_decimal = "1.25"
rust_decimal_macros = "1.25"
